services:
  web:
    build: .
    ports:
      - "5000:5000"
    develop:
      watch:
        - action: sync+restart
          path: .
          target: /app
          ignore:
            - pyproject.toml
            - requirements.txt
        - action: rebuild
          path: uv.lock
