services:
  web:
    build: .
    ports:
      - "8888:8888"
    develop:
      watch:
        - action: sync+restart
          path: .
          target: /app
          ignore:
            - pyproject.toml
            - requirements.txt
            - README.md
            - k8s/
        - action: rebuild
          path: uv.lock
